version: '3.8'

services:
    postgres:
        image: postgres:16
        container_name: postgres-hornet
        restart: unless-stopped
        environment:
            POSTGRES_DB: hornet
            POSTGRES_USER: hornet
            POSTGRES_PASSWORD: hornet
        ports:
            - "5437:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data

volumes:
    pg_data:
